f1_dbt:                      # <-- MUST match `profile:` in dbt_project.yml
  target: dev
  outputs:
    dev:
      type: postgres
      host: localhost        # change if your DB isn't local
      user: postgres         # your DB user
      password: admin    # or use env_var
      port: 5432
      dbname: formula1             # your actual DB name
      schema: f1_stg  # where dbt WRITES in dev
      threads: 4
    prod:
      type: postgres
      host: localhost
      user: postgres
      password: admin
      port: 5432
      dbname: formula1             # typically same DB; different schema
      schema: f1_prod      # where dbt WRITES in prod
      threads: 8